In [5]:
import pandas as pd

# Generación DataFrames

Se desea crear el siguiente DataFrame. Debe generarlo de diferentes maneras

|   | Fruta   | Color     | Precio |
|---|---------|-----------|--------|
| 0 | Manzana | rojo      | 1.5    |
| 1 | Naranja | naranja   | 2.0    |
| 2 | Banana  | amarillo  | 3.4    |
| 3 | Limon   | amarillo  | 2.6    |

1. A partir de un diccionario que tenga en las claves el nombre de las columnas

In [9]:
dicc = {
    "Fruta": ["Manzana", "Naranja", "Banana", "Limon"],
    "Color": ["rojo", "naranja", "amarillo", "amarillo"],
    "Precio": [1.5, 2, 3.4, 2.6]
}
pd.DataFrame(dicc)

     Fruta     Color  Precio
0  Manzana      rojo     1.5
1  Naranja   naranja     2.0
2   Banana  amarillo     3.4
3    Limon  amarillo     2.6

2. A partir de un diccionario que tenga en las claves el indice de las filas (ver from_dict)

In [11]:
dicc = {
    "Fruta": ["Manzana", "Naranja", "Banana", "Limon"],
    "Color": ["rojo", "naranja", "amarillo", "amarillo"],
    "Precio": [1.5, 2, 3.4, 2.6]
}
pd.DataFrame.from_dict(dicc, orient = "index")

              0        1         2         3
Fruta   Manzana  Naranja    Banana     Limon
Color      rojo  naranja  amarillo  amarillo
Precio      1.5        2       3.4       2.6

3. A partir de un diccionario que tenga en las claves el nombre de las columnas, pero que sea un diccionario que tenga además la clave "costo" con los valores (1,1.5,3,2). Por lo que deberá seleccionar únicamente las columnas que le interesen de dicho diccionario

In [13]:
dicc = {
    "Fruta": ["Manzana", "Naranja", "Banana", "Limon"],
    "Color": ["rojo", "naranja", "amarillo", "amarillo"],
    "Precio": [1.5, 2, 3.4, 2.6],
    "Costo": [1, 1.5, 3, 2]
}
pd.DataFrame(dicc,columns = ["Fruta", "Color", "Precio"])

     Fruta     Color  Precio
0  Manzana      rojo     1.5
1  Naranja   naranja     2.0
2   Banana  amarillo     3.4
3    Limon  amarillo     2.6

4. A partir de una lista

In [15]:
lista = [["Manzana","rojo",1.5], ["Naranja","naranja",2], ["Banana","amarillo",3.4], ["Limon","amarillo",2.6]]
pd.DataFrame(
    lista,
    columns = ["Fruta", "Color", "Precio"]
)

     Fruta     Color  Precio
0  Manzana      rojo     1.5
1  Naranja   naranja     2.0
2   Banana  amarillo     3.4
3    Limon  amarillo     2.6

5. A partir de una lista de diccionarios

In [17]:
lista = [
    {"Fruta": "Manzana","Color": "rojo"    ,"Precio": 1.5}, 
    {"Fruta": "Naranja","Color": "naranja" ,"Precio": 2}, 
    {"Fruta": "Banana" ,"Color": "amarillo","Precio": 3.4}, 
    {"Fruta": "Limon"  ,"Color": "amarillo","Precio": 2.6}
]
pd.DataFrame(
    lista
)

     Fruta     Color  Precio
0  Manzana      rojo     1.5
1  Naranja   naranja     2.0
2   Banana  amarillo     3.4
3    Limon  amarillo     2.6

6. A partir de una lista de tuplas generada con la función zip

In [19]:
Fruta  = ["Manzana", "Naranja", "Banana", "Limon"]
Color  = ["rojo", "naranja", "amarillo", "amarillo"]
Precio = [1.5, 2, 3.4, 2.6]

items = list(zip(Fruta,Color,Precio))
pd.DataFrame(
    items,
    columns = ["Fruta", "Color", "Precio"]
)

     Fruta     Color  Precio
0  Manzana      rojo     1.5
1  Naranja   naranja     2.0
2   Banana  amarillo     3.4
3    Limon  amarillo     2.6

# Analisis de DataFrame

Todas las preguntas serán en base al dataframe data

In [22]:
# Base de datos de instituciones educativas en colombia
data = pd.read_csv('https://www.datos.gov.co/api/views/qijw-htwa/rows.csv?accessType=DOWNLOAD')

1. Mostrar las primeras 5 filas del DataFrame

In [24]:
data.head(5)

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
0,2016,BOGOTA,INST DE BTO TEC COMERCIAL PITAGORAS ...,URBANA,KR 5 11 67,5665677 / 3429092,YOLANDA ARIAS CRUZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pitagoras@pitagoras.edu.co
1,2016,BOGOTA,GIMNASIO INFANTIL FEDERICO FROEBEL,URBANA,CL 32 SUR 52 A 54,7100349,SANDRA MILENA MENDEZ,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,gimfedebel@hotmail.com
2,2016,BOGOTA,GIMNASIO INFANTIL LOS NIÑOS DEL MAÑANA,URBANA,CL 134 D 47 27,6010350,CLAUDIA BOCACHICA SAENZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,claudialindenibocachica@hotmail.com
3,2016,BOGOTA,COLEGIO FRANCISCO PRIMERO S.S. (IED),URBANA,KR 28 63 64,2126019 -- 2481271,JOSE CUSTODIO GALARZA MORENO,INSTITUCION EDUCATIVA,NaN,NaN,...,4,NaN,OFICIAL,OFICIAL,NO APLICA,NO,A,NaN,NaN,cedalemania12@redp.edu.co
4,2016,BOGOTA,COL SAN JUAN VIANETH ...,URBANA,KR 2 C 3 18 SUR,2804738 -- 4714934,GLORIA ESPERANZA CHUQUIN LAISECA,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,colegiosanjuanviateh@hotmail.com -- colegiosan...

2. Mostrar las últimas 8 filas del DataFrame

In [26]:
data.tail(8)

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
2396,2016,BOGOTA,LIC PARROQ SAN GREGORIO MAGNO ...,URBANA,KR 29 9 47,2477407,RAFAEL HERNANDEZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,COMUNIDAD RELIGIOSA,COMUNIDAD RELIGIOSA,NO APLICA,NO,A,NaN,NaN,lpsgm@tutopia.com
2397,2016,BOGOTA,COLEGIO BRASILIA - BOSA (IED),URBANA,CL 52 A SUR 87 D 45,7831779,NANCY FERNANDEZ RINCON,INSTITUCION EDUCATIVA,NaN,NaN,...,3,NaN,OFICIAL,OFICIAL,NO APLICA,NO,A,NaN,NaN,cedbrasiliabosa7@gmail.com.co
2398,2016,BOGOTA,COLEGIO ANTONIO BARAYA (IED),URBANA,CL 27 SUR 22 A 02,2392403 / 3668171,MARTHA ISABEL BOGOTA TRANCHITA,INSTITUCION EDUCATIVA,NaN,NaN,...,2,NaN,OFICIAL,OFICIAL,NO APLICA,NO,A,NaN,NaN,cedantoniobaraya18@redp.edu.co
2399,2016,BOGOTA,COLEGIO SAN JOSE DE CALASANZ,URBANA,CL 129 88 B 35,6854492 -- 6854495 -- 6803549,GLADIS CUÉLLAR IBAÑEZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,COMUNIDAD RELIGIOSA,COMUNIDAD RELIGIOSA,NO APLICA,NO,A,NaN,NaN,csjcsuba@yahoo.es
2400,2016,BOGOTA,COL NUEVO REINO DE TURINGIA,URBANA,KR 103 B 152 C 34,6830915,RUTH CECILIA CORREA FAJARDO,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,jibnuevoreinodeturingia@hotmail.com - ruth_cec...
2401,2016,BOGOTA,LIC INF GOOFY ...,URBANA,CL 65 F SUR 78 C 32,7761739 / 7762538 / 7753157 /8045802,SANDRA PATRICIA SANTAMARIA OVALLE,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pattysantaco@yahoo.com directoragoofy@gmail....
2402,2016,BOGOTA,LIC APRENDO CON MIS AMIGOS ...,URBANA,CR. 94 NO.29-30,2671099,YANNETH CONSUELO BOLIVAR GAITAN,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,NaN
2403,2016,BOGOTA,JARD INF EL ROSAL DE MI INFANCIA ...,URBANA,TR. 56A NO.45-18 SUR,7242172,ADALGIZA LADINO,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,adalgizaladino@hotmail.com ...

3. Mostrar cantidad de filas y columnas del dataframe

In [28]:
data.shape

(2404, 30)

4. Seleccionar la columna "zona" del Dataframe como un DataFrame, no como Serie.

In [30]:
data[["zona"]]

        zona
0     URBANA
1     URBANA
2     URBANA
3     URBANA
4     URBANA
...      ...
2399  URBANA
2400  URBANA
2401  URBANA
2402  URBANA
2403  URBANA

[2404 rows x 1 columns]

5. Seleccionar la columna "zona" del Dataframe como una Serie.

In [32]:
data["zona"]

0       URBANA
1       URBANA
2       URBANA
3       URBANA
4       URBANA
         ...
2399    URBANA
2400    URBANA
2401    URBANA
2402    URBANA
2403    URBANA
Name: zona, Length: 2404, dtype: object

6. Cambiar el nombre del índice 3 para que su valor sea obs4

In [34]:
data.rename(index = {3: "obs4"})

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
0,2016,BOGOTA,INST DE BTO TEC COMERCIAL PITAGORAS ...,URBANA,KR 5 11 67,5665677 / 3429092,YOLANDA ARIAS CRUZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pitagoras@pitagoras.edu.co
1,2016,BOGOTA,GIMNASIO INFANTIL FEDERICO FROEBEL,URBANA,CL 32 SUR 52 A 54,7100349,SANDRA MILENA MENDEZ,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,gimfedebel@hotmail.com
2,2016,BOGOTA,GIMNASIO INFANTIL LOS NIÑOS DEL MAÑANA,URBANA,CL 134 D 47 27,6010350,CLAUDIA BOCACHICA SAENZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,claudialindenibocachica@hotmail.com
obs4,2016,BOGOTA,COLEGIO FRANCISCO PRIMERO S.S. (IED),URBANA,KR 28 63 64,2126019 -- 2481271,JOSE CUSTODIO GALARZA MORENO,INSTITUCION EDUCATIVA,NaN,NaN,...,4,NaN,OFICIAL,OFICIAL,NO APLICA,NO,A,NaN,NaN,cedalemania12@redp.edu.co
4,2016,BOGOTA,COL SAN JUAN VIANETH ...,URBANA,KR 2 C 3 18 SUR,2804738 -- 4714934,GLORIA ESPERANZA CHUQUIN LAISECA,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,colegiosanjuanviateh@hotmail.com -- colegiosan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399,2016,BOGOTA,COLEGIO SAN JOSE DE CALASANZ,URBANA,CL 129 88 B 35,6854492 -- 6854495 -- 6803549,GLADIS CUÉLLAR IBAÑEZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,COMUNIDAD RELIGIOSA,COMUNIDAD RELIGIOSA,NO APLICA,NO,A,NaN,NaN,csjcsuba@yahoo.es
2400,2016,BOGOTA,COL NUEVO REINO DE TURINGIA,URBANA,KR 103 B 152 C 34,6830915,RUTH CECILIA CORREA FAJARDO,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,jibnuevoreinodeturingia@hotmail.com - ruth_cec...
2401,2016,BOGOTA,LIC INF GOOFY ...,URBANA,CL 65 F SUR 78 C 32,7761739 / 7762538 / 7753157 /8045802,SANDRA PATRICIA SANTAMARIA OVALLE,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pattysantaco@yahoo.com directoragoofy@gmail....
2402,2016,BOGOTA,LIC APRENDO CON MIS AMIGOS ...,URBANA,CR. 94 NO.29-30,2671099,YANNETH CONSUELO BOLIVAR GAITAN,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,NaN
2403,2016,BOGOTA,JARD INF EL ROSAL DE MI INFANCIA ...,URBANA,TR. 56A NO.45-18 SUR,7242172,ADALGIZA LADINO,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,adalgizaladino@hotmail.com ...

7. Seleccionar las columnas secretaria y zona (como indice y como string hacer el subsetting)

In [36]:
data.loc[:,["secretaria", "zona"]]

     secretaria    zona
0        BOGOTA  URBANA
1        BOGOTA  URBANA
2        BOGOTA  URBANA
3        BOGOTA  URBANA
4        BOGOTA  URBANA
...         ...     ...
2399     BOGOTA  URBANA
2400     BOGOTA  URBANA
2401     BOGOTA  URBANA
2402     BOGOTA  URBANA
2403     BOGOTA  URBANA

[2404 rows x 2 columns]

In [37]:
data.iloc[:,[1,3]]

     secretaria    zona
0        BOGOTA  URBANA
1        BOGOTA  URBANA
2        BOGOTA  URBANA
3        BOGOTA  URBANA
4        BOGOTA  URBANA
...         ...     ...
2399     BOGOTA  URBANA
2400     BOGOTA  URBANA
2401     BOGOTA  URBANA
2402     BOGOTA  URBANA
2403     BOGOTA  URBANA

[2404 rows x 2 columns]

8. Seleccionar de la fila 10 a la 15 y las columnas secretaria y zona

In [39]:
data.iloc[10:16,[1,3]]

   secretaria    zona
10     BOGOTA  URBANA
11     BOGOTA  URBANA
12     BOGOTA  URBANA
13     BOGOTA  URBANA
14     BOGOTA  URBANA
15     BOGOTA  URBANA

9. Listar todas las columnas del dataframe

In [41]:
data.columns

Index(['año', 'secretaria', 'nombreestablecimiento', 'zona', 'direccion',
       'telefono', 'nombre_Rector', 'tipo_Establecimiento', 'etnias', 'sector',
       'genero', 'niveles', 'jornadas', 'caracter', 'especialidad', 'grados',
       'modelos_Educativos', 'capacidades_Excepcionales', 'discapacidades',
       'idiomas', 'numero_de_Sedes', 'estado', 'prestador_de_Servicio',
       'propiedad_Planta_Fisica', 'resguardo', 'matricula_Contratada',
       'calendario', 'internado', 'estrato_Socio_Economico',
       'correo_Electronico'],
      dtype='object')

In [42]:
# Base de datos de instituciones educativas en colombia
data = pd.read_csv('https://www.datos.gov.co/api/views/qijw-htwa/rows.csv?accessType=DOWNLOAD')

10. Renombrar los valores de la columna tipo_Establecimiento (buscar cuales son todos los valores únicos) para que los nombres sean 'Centro' e 'Institucion' según corresponda

In [44]:
data["tipo_Establecimiento"].unique()

array(['INSTITUCION EDUCATIVA', 'CENTRO EDUCATIVO'], dtype=object)

In [45]:
# busco los registros de institución educativa
filtro_institucion = data["tipo_Establecimiento"] == 'INSTITUCION EDUCATIVA'
data.loc[filtro_institucion,:]

# Reemplazo en la columna tipo_Establecimiento, 'INSTITUCION EDUCATIVA' por "Institucion"
data.loc[filtro_institucion,"tipo_Establecimiento"] = "Institucion"


# idem para centro educativo
filtro_centro = data["tipo_Establecimiento"] == 'CENTRO EDUCATIVO'
data.loc[filtro_centro,:]

data.loc[filtro_centro,"tipo_Establecimiento"] = "Centro"

data.head(3)

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
0,2016,BOGOTA,INST DE BTO TEC COMERCIAL PITAGORAS ...,URBANA,KR 5 11 67,5665677 / 3429092,YOLANDA ARIAS CRUZ,Institucion,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pitagoras@pitagoras.edu.co
1,2016,BOGOTA,GIMNASIO INFANTIL FEDERICO FROEBEL,URBANA,CL 32 SUR 52 A 54,7100349,SANDRA MILENA MENDEZ,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,gimfedebel@hotmail.com
2,2016,BOGOTA,GIMNASIO INFANTIL LOS NIÑOS DEL MAÑANA,URBANA,CL 134 D 47 27,6010350,CLAUDIA BOCACHICA SAENZ,Institucion,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,claudialindenibocachica@hotmail.com

In [46]:
data.loc[data["tipo_Establecimiento"] == 'INSTITUCION EDUCATIVA',"tipo_Establecimiento"] = "Institucion"
data.loc[data["tipo_Establecimiento"] == 'CENTRO EDUCATIVO',"tipo_Establecimiento"] = "Centro"
data.head(3)

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
0,2016,BOGOTA,INST DE BTO TEC COMERCIAL PITAGORAS ...,URBANA,KR 5 11 67,5665677 / 3429092,YOLANDA ARIAS CRUZ,Institucion,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pitagoras@pitagoras.edu.co
1,2016,BOGOTA,GIMNASIO INFANTIL FEDERICO FROEBEL,URBANA,CL 32 SUR 52 A 54,7100349,SANDRA MILENA MENDEZ,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,gimfedebel@hotmail.com
2,2016,BOGOTA,GIMNASIO INFANTIL LOS NIÑOS DEL MAÑANA,URBANA,CL 134 D 47 27,6010350,CLAUDIA BOCACHICA SAENZ,Institucion,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,claudialindenibocachica@hotmail.com

11. Eliminar la columna resguardo del DataFrame

In [48]:
data.drop(
    labels = ["resguardo"],
    axis = "columns"
)

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,idiomas,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
0,2016,BOGOTA,INST DE BTO TEC COMERCIAL PITAGORAS ...,URBANA,KR 5 11 67,5665677 / 3429092,YOLANDA ARIAS CRUZ,Institucion,NaN,NaN,...,INGLÉS,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO,A,NaN,NaN,pitagoras@pitagoras.edu.co
1,2016,BOGOTA,GIMNASIO INFANTIL FEDERICO FROEBEL,URBANA,CL 32 SUR 52 A 54,7100349,SANDRA MILENA MENDEZ,Centro,NaN,NaN,...,NaN,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO,A,NaN,NaN,gimfedebel@hotmail.com
2,2016,BOGOTA,GIMNASIO INFANTIL LOS NIÑOS DEL MAÑANA,URBANA,CL 134 D 47 27,6010350,CLAUDIA BOCACHICA SAENZ,Institucion,NaN,NaN,...,NaN,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO,A,NaN,NaN,claudialindenibocachica@hotmail.com
3,2016,BOGOTA,COLEGIO FRANCISCO PRIMERO S.S. (IED),URBANA,KR 28 63 64,2126019 -- 2481271,JOSE CUSTODIO GALARZA MORENO,Institucion,NaN,NaN,...,NaN,4,NaN,OFICIAL,OFICIAL,NO,A,NaN,NaN,cedalemania12@redp.edu.co
4,2016,BOGOTA,COL SAN JUAN VIANETH ...,URBANA,KR 2 C 3 18 SUR,2804738 -- 4714934,GLORIA ESPERANZA CHUQUIN LAISECA,Centro,NaN,NaN,...,INGLÉS,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO,A,NaN,NaN,colegiosanjuanviateh@hotmail.com -- colegiosan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399,2016,BOGOTA,COLEGIO SAN JOSE DE CALASANZ,URBANA,CL 129 88 B 35,6854492 -- 6854495 -- 6803549,GLADIS CUÉLLAR IBAÑEZ,Institucion,NaN,NaN,...,NaN,1,NaN,COMUNIDAD RELIGIOSA,COMUNIDAD RELIGIOSA,NO,A,NaN,NaN,csjcsuba@yahoo.es
2400,2016,BOGOTA,COL NUEVO REINO DE TURINGIA,URBANA,KR 103 B 152 C 34,6830915,RUTH CECILIA CORREA FAJARDO,Centro,NaN,NaN,...,INGLÉS,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO,A,NaN,NaN,jibnuevoreinodeturingia@hotmail.com - ruth_cec...
2401,2016,BOGOTA,LIC INF GOOFY ...,URBANA,CL 65 F SUR 78 C 32,7761739 / 7762538 / 7753157 /8045802,SANDRA PATRICIA SANTAMARIA OVALLE,Centro,NaN,NaN,...,FRANCES,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO,A,NaN,NaN,pattysantaco@yahoo.com directoragoofy@gmail....
2402,2016,BOGOTA,LIC APRENDO CON MIS AMIGOS ...,URBANA,CR. 94 NO.29-30,2671099,YANNETH CONSUELO BOLIVAR GAITAN,Centro,NaN,NaN,...,INGLÉS,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO,A,NaN,NaN,NaN
2403,2016,BOGOTA,JARD INF EL ROSAL DE MI INFANCIA ...,URBANA,TR. 56A NO.45-18 SUR,7242172,ADALGIZA LADINO,Centro,NaN,NaN,...,INGLÉS,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO,A,NaN,NaN,adalgizaladino@hotmail.com ...

12. Contar cuantos valores únicos hay en cada columna con la función nunique

In [50]:
data.nunique()

año                             1
secretaria                      1
nombreestablecimiento        2387
zona                            3
direccion                    2377
telefono                     2328
nombre_Rector                2354
tipo_Establecimiento            2
etnias                         11
sector                          0
genero                          0
niveles                        18
jornadas                       41
caracter                        0
especialidad                   21
grados                        180
modelos_Educativos             32
capacidades_Excepcionales       4
discapacidades                124
idiomas                         7
numero_de_Sedes                 7
estado                          0
prestador_de_Servicio          10
propiedad_Planta_Fisica        10
resguardo                       2
matricula_Contratada            2
calendario                      3
internado                       0
estrato_Socio_Economico         2
correo_Electronico           1961
dtype: int64

13. Mostrar un dataframe con los Rectores que esten en más de una institución

In [52]:
data_institucion = data.loc[data["tipo_Establecimiento"] == 'Institucion',:]
data_institucion.loc[data_institucion.duplicated(subset="nombre_Rector"),["nombre_Rector"]]

                      nombre_Rector
358     MARTHA CECILIA JIMENEZ PEÑA
569      MAURICIO SANABRIA GONZALEZ
655            MARIA RANGEL DE RIOS
679        JORGE ROBERTO AMAYA PAVA
954       FELIX EDINSON ANGEL ACUÑA
1058      GRACIELA RODRIGUEZ POVEDA
1529  LUIS FERNANDO MURCIA ANGARITA
1553  VICTOR MANUEL NEIRA RODRIGUEZ
1785       GUSTAVO MENDEZ HERNANDEZ
2225         ALBENIO BOLIVAR MONROY
2357  HNA CONCEPCION AMEZQUITA DIAZ

14. Contar cuantos registros no nulos hay en cada fila y almacenarlo en un diccionario que tenga de clave el indice de la fila

In [54]:
dicc = {}
for indice, fila in data.iterrows():
    nulos = data.loc[indice,].isnull()
    dicc[indice] = sum(nulos)
print(dicc)

{0: 9, 1: 11, 2: 11, 3: 10, 4: 10, 5: 9, 6: 10, 7: 10, 8: 10, 9: 9, 10: 11, 11: 10, 12: 10, 13: 9, 14: 11, 15: 11, 16: 10, 17: 9, 18: 10, 19: 12, 20: 9, 21: 15, 22: 9, 23: 10, 24: 10, 25: 12, 26: 10, 27: 10, 28: 10, 29: 10, 30: 11, 31: 10, 32: 10, 33: 8, 34: 10, 35: 11, 36: 9, 37: 10, 38: 10, 39: 11, 40: 12, 41: 11, 42: 9, 43: 10, 44: 10, 45: 11, 46: 9, 47: 10, 48: 10, 49: 9, 50: 9, 51: 11, 52: 13, 53: 11, 54: 10, 55: 11, 56: 9, 57: 12, 58: 10, 59: 11, 60: 8, 61: 9, 62: 11, 63: 9, 64: 10, 65: 15, 66: 10, 67: 9, 68: 10, 69: 11, 70: 10, 71: 10, 72: 9, 73: 10, 74: 10, 75: 10, 76: 11, 77: 10, 78: 10, 79: 9, 80: 10, 81: 10, 82: 8, 83: 11, 84: 12, 85: 10, 86: 10, 87: 10, 88: 9, 89: 11, 90: 11, 91: 9, 92: 13, 93: 12, 94: 11, 95: 10, 96: 10, 97: 10, 98: 10, 99: 9, 100: 9, 101: 10, 102: 11, 103: 10, 104: 10, 105: 10, 106: 9, 107: 9, 108: 10, 109: 11, 110: 9, 111: 10, 112: 10, 113: 8, 114: 11, 115: 9, 116: 11, 117: 10, 118: 10, 119: 11, 120: 9, 121: 10, 122: 10, 123: 10, 124: 8, 125: 11, 126: 11, 127: 10, 128: 10, 129: 9, 130: 11, 131: 10, 132: 10, 133: 12, 134: 9, 135: 10, 136: 10, 137: 9, 138: 10, 139: 11, 140: 11, 141: 9, 142: 10, 143: 11, 144: 9, 145: 10, 146: 10, 147: 10, 148: 9, 149: 9, 150: 11, 151: 11, 152: 10, 153: 9, 154: 10, 155: 10, 156: 12, 157: 10, 158: 10, 159: 10, 160: 9, 161: 10, 162: 11, 163: 9, 164: 10, 165: 11, 166: 9, 167: 11, 168: 11, 169: 11, 170: 9, 171: 10, 172: 10, 173: 11, 174: 10, 175: 9, 176: 10, 177: 9, 178: 11, 179: 9, 180: 11, 181: 10, 182: 10, 183: 13, 184: 11, 185: 9, 186: 10, 187: 10, 188: 11, 189: 9, 190: 10, 191: 9, 192: 9, 193: 10, 194: 10, 195: 9, 196: 10, 197: 9, 198: 13, 199: 11, 200: 11, 201: 10, 202: 10, 203: 11, 204: 10, 205: 9, 206: 11, 207: 10, 208: 11, 209: 11, 210: 11, 211: 10, 212: 10, 213: 9, 214: 10, 215: 9, 216: 11, 217: 13, 218: 11, 219: 10, 220: 11, 221: 11, 222: 10, 223: 9, 224: 9, 225: 10, 226: 11, 227: 9, 228: 9, 229: 11, 230: 10, 231: 12, 232: 9, 233: 10, 234: 9, 235: 12, 236: 13, 237: 11, 238: 11, 239: 9, 240: 11, 241: 8, 242: 11, 243: 10, 244: 11, 245: 9, 246: 10, 247: 10, 248: 10, 249: 9, 250: 10, 251: 10, 252: 10, 253: 8, 254: 9, 255: 10, 256: 10, 257: 10, 258: 10, 259: 11, 260: 10, 261: 10, 262: 10, 263: 6, 264: 11, 265: 10, 266: 11, 267: 10, 268: 10, 269: 9, 270: 10, 271: 11, 272: 10, 273: 10, 274: 11, 275: 9, 276: 9, 277: 9, 278: 10, 279: 11, 280: 10, 281: 10, 282: 11, 283: 10, 284: 10, 285: 10, 286: 11, 287: 10, 288: 10, 289: 11, 290: 10, 291: 10, 292: 9, 293: 10, 294: 10, 295: 10, 296: 9, 297: 11, 298: 10, 299: 11, 300: 10, 301: 11, 302: 10, 303: 9, 304: 10, 305: 11, 306: 9, 307: 10, 308: 11, 309: 10, 310: 9, 311: 10, 312: 10, 313: 10, 314: 9, 315: 10, 316: 10, 317: 8, 318: 10, 319: 10, 320: 10, 321: 10, 322: 10, 323: 10, 324: 12, 325: 11, 326: 10, 327: 9, 328: 10, 329: 10, 330: 11, 331: 11, 332: 10, 333: 9, 334: 10, 335: 9, 336: 10, 337: 9, 338: 9, 339: 10, 340: 10, 341: 10, 342: 10, 343: 10, 344: 8, 345: 10, 346: 10, 347: 10, 348: 9, 349: 10, 350: 11, 351: 10, 352: 10, 353: 10, 354: 11, 355: 9, 356: 10, 357: 10, 358: 8, 359: 9, 360: 9, 361: 10, 362: 10, 363: 10, 364: 10, 365: 9, 366: 10, 367: 11, 368: 11, 369: 8, 370: 9, 371: 10, 372: 11, 373: 11, 374: 9, 375: 10, 376: 11, 377: 10, 378: 9, 379: 11, 380: 11, 381: 11, 382: 10, 383: 9, 384: 8, 385: 9, 386: 9, 387: 11, 388: 8, 389: 10, 390: 10, 391: 9, 392: 10, 393: 10, 394: 10, 395: 10, 396: 9, 397: 11, 398: 10, 399: 8, 400: 10, 401: 11, 402: 13, 403: 9, 404: 11, 405: 11, 406: 9, 407: 10, 408: 10, 409: 10, 410: 9, 411: 9, 412: 10, 413: 10, 414: 9, 415: 11, 416: 10, 417: 10, 418: 9, 419: 10, 420: 12, 421: 11, 422: 10, 423: 10, 424: 10, 425: 11, 426: 10, 427: 9, 428: 10, 429: 9, 430: 9, 431: 10, 432: 8, 433: 11, 434: 9, 435: 10, 436: 8, 437: 10, 438: 10, 439: 9, 440: 8, 441: 9, 442: 9, 443: 8, 444: 10, 445: 11, 446: 10, 447: 10, 448: 9, 449: 8, 450: 10, 451: 10, 452: 10, 453: 11, 454: 10, 455: 11, 456: 9, 457: 11, 458: 11, 459: 12, 460: 11, 461: 13, 462: 8, 463: 10, 464: 10, 465: 10, 466: 10, 467: 9, 468: 9, 469: 11, 470: 11, 471: 11, 472: 11, 473: 11, 474: 11, 475: 9, 476: 9, 477: 10, 478: 11, 479: 10, 480: 11, 481: 9, 482: 9, 483: 10, 484: 9, 485: 11, 486: 10, 487: 12, 488: 11, 489: 11, 490: 10, 491: 11, 492: 10, 493: 9, 494: 10, 495: 15, 496: 12, 497: 10, 498: 12, 499: 10, 500: 11, 501: 10, 502: 8, 503: 9, 504: 10, 505: 10, 506: 10, 507: 8, 508: 12, 509: 10, 510: 10, 511: 9, 512: 9, 513: 10, 514: 10, 515: 9, 516: 11, 517: 10, 518: 9, 519: 9, 520: 11, 521: 9, 522: 11, 523: 11, 524: 11, 525: 12, 526: 10, 527: 10, 528: 10, 529: 9, 530: 10, 531: 11, 532: 9, 533: 10, 534: 9, 535: 9, 536: 11, 537: 9, 538: 10, 539: 13, 540: 10, 541: 9, 542: 10, 543: 11, 544: 10, 545: 10, 546: 10, 547: 12, 548: 11, 549: 10, 550: 11, 551: 9, 552: 10, 553: 9, 554: 11, 555: 9, 556: 12, 557: 11, 558: 11, 559: 9, 560: 10, 561: 9, 562: 10, 563: 9, 564: 10, 565: 10, 566: 10, 567: 10, 568: 10, 569: 8, 570: 9, 571: 9, 572: 10, 573: 12, 574: 9, 575: 9, 576: 11, 577: 10, 578: 10, 579: 12, 580: 11, 581: 12, 582: 11, 583: 12, 584: 11, 585: 11, 586: 9, 587: 9, 588: 10, 589: 11, 590: 10, 591: 9, 592: 10, 593: 10, 594: 9, 595: 8, 596: 11, 597: 10, 598: 9, 599: 11, 600: 11, 601: 11, 602: 11, 603: 11, 604: 10, 605: 11, 606: 10, 607: 11, 608: 9, 609: 10, 610: 10, 611: 10, 612: 10, 613: 9, 614: 9, 615: 10, 616: 9, 617: 11, 618: 10, 619: 10, 620: 10, 621: 10, 622: 11, 623: 10, 624: 8, 625: 9, 626: 10, 627: 11, 628: 9, 629: 9, 630: 10, 631: 9, 632: 8, 633: 10, 634: 11, 635: 10, 636: 13, 637: 11, 638: 9, 639: 10, 640: 10, 641: 11, 642: 8, 643: 10, 644: 10, 645: 10, 646: 10, 647: 10, 648: 10, 649: 10, 650: 9, 651: 10, 652: 10, 653: 8, 654: 10, 655: 10, 656: 10, 657: 10, 658: 9, 659: 10, 660: 10, 661: 10, 662: 10, 663: 10, 664: 10, 665: 11, 666: 13, 667: 10, 668: 10, 669: 9, 670: 9, 671: 10, 672: 9, 673: 11, 674: 10, 675: 11, 676: 10, 677: 9, 678: 9, 679: 10, 680: 10, 681: 8, 682: 10, 683: 11, 684: 11, 685: 8, 686: 11, 687: 11, 688: 9, 689: 9, 690: 9, 691: 10, 692: 11, 693: 9, 694: 10, 695: 10, 696: 9, 697: 10, 698: 9, 699: 10, 700: 9, 701: 9, 702: 11, 703: 9, 704: 11, 705: 10, 706: 10, 707: 9, 708: 10, 709: 11, 710: 8, 711: 9, 712: 11, 713: 9, 714: 12, 715: 10, 716: 10, 717: 11, 718: 11, 719: 11, 720: 11, 721: 10, 722: 10, 723: 9, 724: 11, 725: 12, 726: 9, 727: 10, 728: 10, 729: 12, 730: 11, 731: 10, 732: 11, 733: 10, 734: 10, 735: 11, 736: 10, 737: 13, 738: 10, 739: 10, 740: 10, 741: 11, 742: 10, 743: 9, 744: 9, 745: 10, 746: 11, 747: 10, 748: 9, 749: 12, 750: 9, 751: 10, 752: 10, 753: 11, 754: 9, 755: 12, 756: 10, 757: 11, 758: 10, 759: 10, 760: 9, 761: 11, 762: 10, 763: 10, 764: 10, 765: 10, 766: 9, 767: 10, 768: 10, 769: 10, 770: 8, 771: 10, 772: 13, 773: 11, 774: 9, 775: 10, 776: 9, 777: 10, 778: 8, 779: 10, 780: 9, 781: 9, 782: 9, 783: 11, 784: 9, 785: 8, 786: 11, 787: 10, 788: 11, 789: 10, 790: 10, 791: 9, 792: 10, 793: 11, 794: 10, 795: 9, 796: 9, 797: 11, 798: 11, 799: 10, 800: 11, 801: 11, 802: 9, 803: 11, 804: 11, 805: 11, 806: 10, 807: 10, 808: 10, 809: 11, 810: 17, 811: 10, 812: 10, 813: 9, 814: 10, 815: 10, 816: 12, 817: 10, 818: 9, 819: 11, 820: 10, 821: 10, 822: 9, 823: 10, 824: 9, 825: 11, 826: 11, 827: 10, 828: 9, 829: 11, 830: 11, 831: 9, 832: 11, 833: 9, 834: 10, 835: 10, 836: 10, 837: 10, 838: 10, 839: 10, 840: 10, 841: 8, 842: 11, 843: 9, 844: 11, 845: 11, 846: 11, 847: 10, 848: 11, 849: 16, 850: 11, 851: 11, 852: 10, 853: 11, 854: 9, 855: 10, 856: 10, 857: 10, 858: 11, 859: 8, 860: 9, 861: 10, 862: 10, 863: 9, 864: 10, 865: 13, 866: 11, 867: 11, 868: 9, 869: 10, 870: 9, 871: 12, 872: 11, 873: 8, 874: 12, 875: 10, 876: 9, 877: 9, 878: 11, 879: 10, 880: 9, 881: 11, 882: 8, 883: 9, 884: 10, 885: 11, 886: 10, 887: 10, 888: 8, 889: 10, 890: 11, 891: 11, 892: 10, 893: 10, 894: 9, 895: 10, 896: 9, 897: 10, 898: 9, 899: 11, 900: 9, 901: 9, 902: 8, 903: 9, 904: 10, 905: 10, 906: 11, 907: 9, 908: 10, 909: 10, 910: 10, 911: 10, 912: 11, 913: 10, 914: 10, 915: 12, 916: 9, 917: 12, 918: 10, 919: 9, 920: 10, 921: 12, 922: 10, 923: 9, 924: 12, 925: 9, 926: 10, 927: 9, 928: 11, 929: 9, 930: 11, 931: 10, 932: 10, 933: 10, 934: 10, 935: 10, 936: 10, 937: 12, 938: 11, 939: 10, 940: 10, 941: 11, 942: 9, 943: 11, 944: 9, 945: 12, 946: 11, 947: 10, 948: 11, 949: 11, 950: 10, 951: 10, 952: 10, 953: 11, 954: 11, 955: 11, 956: 10, 957: 9, 958: 12, 959: 10, 960: 10, 961: 10, 962: 10, 963: 10, 964: 10, 965: 11, 966: 10, 967: 10, 968: 9, 969: 13, 970: 9, 971: 9, 972: 9, 973: 13, 974: 10, 975: 11, 976: 10, 977: 9, 978: 10, 979: 10, 980: 9, 981: 10, 982: 11, 983: 10, 984: 10, 985: 12, 986: 10, 987: 10, 988: 9, 989: 10, 990: 12, 991: 9, 992: 10, 993: 10, 994: 9, 995: 10, 996: 10, 997: 10, 998: 10, 999: 10, 1000: 12, 1001: 11, 1002: 8, 1003: 9, 1004: 10, 1005: 10, 1006: 11, 1007: 12, 1008: 11, 1009: 8, 1010: 9, 1011: 10, 1012: 7, 1013: 9, 1014: 12, 1015: 9, 1016: 10, 1017: 10, 1018: 9, 1019: 11, 1020: 11, 1021: 9, 1022: 10, 1023: 10, 1024: 9, 1025: 10, 1026: 11, 1027: 8, 1028: 9, 1029: 11, 1030: 9, 1031: 10, 1032: 10, 1033: 12, 1034: 10, 1035: 8, 1036: 10, 1037: 10, 1038: 10, 1039: 10, 1040: 10, 1041: 10, 1042: 9, 1043: 10, 1044: 11, 1045: 10, 1046: 9, 1047: 10, 1048: 10, 1049: 8, 1050: 10, 1051: 10, 1052: 10, 1053: 8, 1054: 11, 1055: 10, 1056: 10, 1057: 11, 1058: 10, 1059: 10, 1060: 12, 1061: 11, 1062: 9, 1063: 9, 1064: 9, 1065: 10, 1066: 9, 1067: 9, 1068: 9, 1069: 9, 1070: 10, 1071: 9, 1072: 11, 1073: 8, 1074: 10, 1075: 10, 1076: 10, 1077: 10, 1078: 11, 1079: 10, 1080: 10, 1081: 9, 1082: 9, 1083: 11, 1084: 9, 1085: 9, 1086: 10, 1087: 10, 1088: 9, 1089: 10, 1090: 11, 1091: 10, 1092: 8, 1093: 11, 1094: 9, 1095: 10, 1096: 9, 1097: 10, 1098: 11, 1099: 9, 1100: 9, 1101: 11, 1102: 9, 1103: 9, 1104: 11, 1105: 9, 1106: 10, 1107: 10, 1108: 11, 1109: 10, 1110: 9, 1111: 11, 1112: 8, 1113: 12, 1114: 10, 1115: 12, 1116: 10, 1117: 10, 1118: 11, 1119: 10, 1120: 10, 1121: 10, 1122: 9, 1123: 11, 1124: 11, 1125: 9, 1126: 9, 1127: 11, 1128: 10, 1129: 9, 1130: 10, 1131: 10, 1132: 8, 1133: 9, 1134: 10, 1135: 10, 1136: 11, 1137: 9, 1138: 9, 1139: 9, 1140: 9, 1141: 11, 1142: 11, 1143: 11, 1144: 8, 1145: 11, 1146: 9, 1147: 9, 1148: 11, 1149: 10, 1150: 10, 1151: 11, 1152: 9, 1153: 10, 1154: 11, 1155: 10, 1156: 11, 1157: 12, 1158: 11, 1159: 10, 1160: 11, 1161: 10, 1162: 12, 1163: 10, 1164: 10, 1165: 9, 1166: 11, 1167: 9, 1168: 10, 1169: 10, 1170: 11, 1171: 11, 1172: 11, 1173: 9, 1174: 10, 1175: 9, 1176: 12, 1177: 13, 1178: 9, 1179: 11, 1180: 12, 1181: 10, 1182: 10, 1183: 9, 1184: 10, 1185: 11, 1186: 10, 1187: 10, 1188: 10, 1189: 11, 1190: 9, 1191: 9, 1192: 11, 1193: 10, 1194: 8, 1195: 10, 1196: 10, 1197: 10, 1198: 11, 1199: 11, 1200: 10, 1201: 10, 1202: 9, 1203: 11, 1204: 9, 1205: 10, 1206: 11, 1207: 10, 1208: 11, 1209: 9, 1210: 9, 1211: 8, 1212: 10, 1213: 11, 1214: 11, 1215: 9, 1216: 9, 1217: 10, 1218: 10, 1219: 10, 1220: 10, 1221: 11, 1222: 13, 1223: 11, 1224: 8, 1225: 10, 1226: 10, 1227: 9, 1228: 11, 1229: 9, 1230: 10, 1231: 10, 1232: 9, 1233: 9, 1234: 10, 1235: 10, 1236: 10, 1237: 10, 1238: 10, 1239: 9, 1240: 10, 1241: 10, 1242: 10, 1243: 10, 1244: 11, 1245: 10, 1246: 9, 1247: 11, 1248: 9, 1249: 10, 1250: 9, 1251: 12, 1252: 11, 1253: 10, 1254: 10, 1255: 9, 1256: 10, 1257: 10, 1258: 11, 1259: 11, 1260: 10, 1261: 10, 1262: 10, 1263: 10, 1264: 10, 1265: 11, 1266: 10, 1267: 10, 1268: 10, 1269: 10, 1270: 8, 1271: 9, 1272: 12, 1273: 10, 1274: 10, 1275: 9, 1276: 11, 1277: 9, 1278: 9, 1279: 12, 1280: 10, 1281: 10, 1282: 10, 1283: 10, 1284: 9, 1285: 11, 1286: 8, 1287: 11, 1288: 8, 1289: 12, 1290: 11, 1291: 11, 1292: 10, 1293: 14, 1294: 10, 1295: 10, 1296: 11, 1297: 10, 1298: 10, 1299: 8, 1300: 10, 1301: 10, 1302: 10, 1303: 11, 1304: 10, 1305: 10, 1306: 10, 1307: 9, 1308: 10, 1309: 9, 1310: 10, 1311: 7, 1312: 10, 1313: 9, 1314: 10, 1315: 11, 1316: 10, 1317: 10, 1318: 10, 1319: 11, 1320: 10, 1321: 11, 1322: 10, 1323: 11, 1324: 8, 1325: 11, 1326: 10, 1327: 9, 1328: 9, 1329: 12, 1330: 10, 1331: 10, 1332: 10, 1333: 11, 1334: 9, 1335: 10, 1336: 10, 1337: 11, 1338: 10, 1339: 10, 1340: 9, 1341: 10, 1342: 10, 1343: 10, 1344: 11, 1345: 11, 1346: 10, 1347: 11, 1348: 9, 1349: 10, 1350: 10, 1351: 9, 1352: 9, 1353: 10, 1354: 10, 1355: 10, 1356: 11, 1357: 11, 1358: 10, 1359: 11, 1360: 9, 1361: 11, 1362: 10, 1363: 8, 1364: 11, 1365: 10, 1366: 10, 1367: 9, 1368: 10, 1369: 10, 1370: 11, 1371: 10, 1372: 10, 1373: 10, 1374: 8, 1375: 9, 1376: 11, 1377: 10, 1378: 9, 1379: 11, 1380: 10, 1381: 9, 1382: 11, 1383: 12, 1384: 11, 1385: 10, 1386: 11, 1387: 10, 1388: 12, 1389: 12, 1390: 10, 1391: 9, 1392: 10, 1393: 12, 1394: 9, 1395: 10, 1396: 9, 1397: 10, 1398: 10, 1399: 11, 1400: 11, 1401: 9, 1402: 9, 1403: 9, 1404: 11, 1405: 10, 1406: 13, 1407: 11, 1408: 10, 1409: 10, 1410: 8, 1411: 11, 1412: 10, 1413: 10, 1414: 10, 1415: 10, 1416: 10, 1417: 8, 1418: 10, 1419: 9, 1420: 10, 1421: 11, 1422: 9, 1423: 11, 1424: 10, 1425: 11, 1426: 10, 1427: 10, 1428: 10, 1429: 10, 1430: 10, 1431: 11, 1432: 10, 1433: 10, 1434: 11, 1435: 10, 1436: 10, 1437: 10, 1438: 11, 1439: 9, 1440: 10, 1441: 9, 1442: 10, 1443: 9, 1444: 11, 1445: 10, 1446: 11, 1447: 9, 1448: 10, 1449: 10, 1450: 9, 1451: 10, 1452: 10, 1453: 13, 1454: 10, 1455: 9, 1456: 11, 1457: 10, 1458: 10, 1459: 9, 1460: 10, 1461: 9, 1462: 10, 1463: 9, 1464: 13, 1465: 12, 1466: 10, 1467: 9, 1468: 11, 1469: 11, 1470: 10, 1471: 11, 1472: 9, 1473: 10, 1474: 9, 1475: 12, 1476: 10, 1477: 10, 1478: 12, 1479: 10, 1480: 10, 1481: 9, 1482: 10, 1483: 10, 1484: 10, 1485: 11, 1486: 9, 1487: 10, 1488: 9, 1489: 9, 1490: 11, 1491: 10, 1492: 10, 1493: 10, 1494: 12, 1495: 10, 1496: 8, 1497: 10, 1498: 13, 1499: 10, 1500: 10, 1501: 9, 1502: 10, 1503: 11, 1504: 10, 1505: 10, 1506: 10, 1507: 10, 1508: 10, 1509: 8, 1510: 10, 1511: 10, 1512: 12, 1513: 11, 1514: 11, 1515: 8, 1516: 10, 1517: 10, 1518: 10, 1519: 10, 1520: 8, 1521: 10, 1522: 10, 1523: 10, 1524: 9, 1525: 11, 1526: 10, 1527: 10, 1528: 9, 1529: 9, 1530: 10, 1531: 11, 1532: 11, 1533: 13, 1534: 11, 1535: 10, 1536: 7, 1537: 9, 1538: 10, 1539: 10, 1540: 10, 1541: 10, 1542: 11, 1543: 11, 1544: 10, 1545: 17, 1546: 10, 1547: 8, 1548: 10, 1549: 10, 1550: 10, 1551: 9, 1552: 11, 1553: 9, 1554: 10, 1555: 10, 1556: 9, 1557: 10, 1558: 9, 1559: 10, 1560: 9, 1561: 11, 1562: 11, 1563: 10, 1564: 9, 1565: 12, 1566: 8, 1567: 11, 1568: 8, 1569: 9, 1570: 12, 1571: 10, 1572: 10, 1573: 10, 1574: 9, 1575: 12, 1576: 10, 1577: 10, 1578: 10, 1579: 10, 1580: 10, 1581: 11, 1582: 8, 1583: 11, 1584: 11, 1585: 11, 1586: 10, 1587: 9, 1588: 10, 1589: 10, 1590: 10, 1591: 10, 1592: 9, 1593: 9, 1594: 10, 1595: 10, 1596: 10, 1597: 11, 1598: 10, 1599: 12, 1600: 10, 1601: 10, 1602: 10, 1603: 10, 1604: 9, 1605: 12, 1606: 9, 1607: 16, 1608: 11, 1609: 10, 1610: 7, 1611: 11, 1612: 11, 1613: 10, 1614: 10, 1615: 8, 1616: 10, 1617: 11, 1618: 9, 1619: 10, 1620: 11, 1621: 10, 1622: 11, 1623: 11, 1624: 10, 1625: 9, 1626: 9, 1627: 10, 1628: 10, 1629: 11, 1630: 9, 1631: 10, 1632: 10, 1633: 11, 1634: 10, 1635: 11, 1636: 11, 1637: 10, 1638: 13, 1639: 11, 1640: 11, 1641: 10, 1642: 10, 1643: 11, 1644: 10, 1645: 10, 1646: 10, 1647: 10, 1648: 10, 1649: 12, 1650: 10, 1651: 10, 1652: 10, 1653: 10, 1654: 11, 1655: 10, 1656: 10, 1657: 10, 1658: 10, 1659: 9, 1660: 10, 1661: 10, 1662: 9, 1663: 10, 1664: 9, 1665: 10, 1666: 11, 1667: 9, 1668: 9, 1669: 10, 1670: 11, 1671: 10, 1672: 8, 1673: 10, 1674: 10, 1675: 9, 1676: 10, 1677: 11, 1678: 10, 1679: 9, 1680: 12, 1681: 10, 1682: 11, 1683: 9, 1684: 11, 1685: 10, 1686: 10, 1687: 10, 1688: 10, 1689: 9, 1690: 9, 1691: 11, 1692: 10, 1693: 10, 1694: 9, 1695: 11, 1696: 9, 1697: 10, 1698: 10, 1699: 10, 1700: 10, 1701: 11, 1702: 10, 1703: 11, 1704: 10, 1705: 10, 1706: 10, 1707: 11, 1708: 10, 1709: 10, 1710: 10, 1711: 10, 1712: 10, 1713: 10, 1714: 11, 1715: 10, 1716: 10, 1717: 11, 1718: 10, 1719: 9, 1720: 10, 1721: 9, 1722: 10, 1723: 11, 1724: 10, 1725: 11, 1726: 10, 1727: 9, 1728: 10, 1729: 9, 1730: 10, 1731: 10, 1732: 10, 1733: 10, 1734: 9, 1735: 8, 1736: 11, 1737: 9, 1738: 8, 1739: 10, 1740: 10, 1741: 10, 1742: 10, 1743: 11, 1744: 10, 1745: 11, 1746: 10, 1747: 9, 1748: 11, 1749: 11, 1750: 11, 1751: 11, 1752: 10, 1753: 11, 1754: 10, 1755: 10, 1756: 10, 1757: 10, 1758: 11, 1759: 9, 1760: 11, 1761: 9, 1762: 10, 1763: 11, 1764: 9, 1765: 11, 1766: 10, 1767: 9, 1768: 11, 1769: 8, 1770: 12, 1771: 10, 1772: 13, 1773: 14, 1774: 10, 1775: 10, 1776: 11, 1777: 10, 1778: 11, 1779: 11, 1780: 13, 1781: 10, 1782: 10, 1783: 10, 1784: 8, 1785: 10, 1786: 8, 1787: 8, 1788: 8, 1789: 8, 1790: 10, 1791: 8, 1792: 10, 1793: 11, 1794: 10, 1795: 10, 1796: 8, 1797: 10, 1798: 8, 1799: 11, 1800: 11, 1801: 11, 1802: 11, 1803: 8, 1804: 10, 1805: 10, 1806: 11, 1807: 10, 1808: 11, 1809: 8, 1810: 9, 1811: 11, 1812: 12, 1813: 10, 1814: 11, 1815: 10, 1816: 11, 1817: 12, 1818: 8, 1819: 11, 1820: 9, 1821: 10, 1822: 10, 1823: 9, 1824: 9, 1825: 13, 1826: 11, 1827: 9, 1828: 11, 1829: 10, 1830: 11, 1831: 8, 1832: 10, 1833: 7, 1834: 10, 1835: 7, 1836: 11, 1837: 10, 1838: 9, 1839: 10, 1840: 9, 1841: 10, 1842: 10, 1843: 10, 1844: 12, 1845: 10, 1846: 10, 1847: 10, 1848: 11, 1849: 9, 1850: 11, 1851: 11, 1852: 10, 1853: 11, 1854: 10, 1855: 10, 1856: 9, 1857: 9, 1858: 11, 1859: 10, 1860: 9, 1861: 12, 1862: 11, 1863: 9, 1864: 10, 1865: 11, 1866: 10, 1867: 10, 1868: 10, 1869: 10, 1870: 10, 1871: 10, 1872: 7, 1873: 11, 1874: 11, 1875: 10, 1876: 10, 1877: 11, 1878: 10, 1879: 10, 1880: 10, 1881: 10, 1882: 8, 1883: 9, 1884: 10, 1885: 11, 1886: 10, 1887: 9, 1888: 9, 1889: 11, 1890: 11, 1891: 11, 1892: 10, 1893: 10, 1894: 11, 1895: 10, 1896: 10, 1897: 8, 1898: 10, 1899: 9, 1900: 10, 1901: 10, 1902: 10, 1903: 11, 1904: 9, 1905: 10, 1906: 11, 1907: 11, 1908: 10, 1909: 10, 1910: 9, 1911: 10, 1912: 10, 1913: 10, 1914: 10, 1915: 11, 1916: 10, 1917: 10, 1918: 10, 1919: 10, 1920: 10, 1921: 11, 1922: 11, 1923: 11, 1924: 12, 1925: 10, 1926: 10, 1927: 11, 1928: 10, 1929: 10, 1930: 10, 1931: 10, 1932: 8, 1933: 10, 1934: 10, 1935: 10, 1936: 9, 1937: 9, 1938: 11, 1939: 9, 1940: 10, 1941: 10, 1942: 9, 1943: 11, 1944: 9, 1945: 9, 1946: 10, 1947: 11, 1948: 11, 1949: 9, 1950: 10, 1951: 10, 1952: 10, 1953: 10, 1954: 9, 1955: 9, 1956: 10, 1957: 10, 1958: 10, 1959: 9, 1960: 7, 1961: 11, 1962: 10, 1963: 9, 1964: 7, 1965: 11, 1966: 9, 1967: 10, 1968: 9, 1969: 9, 1970: 9, 1971: 11, 1972: 10, 1973: 9, 1974: 9, 1975: 11, 1976: 11, 1977: 11, 1978: 10, 1979: 10, 1980: 9, 1981: 10, 1982: 9, 1983: 10, 1984: 9, 1985: 11, 1986: 10, 1987: 8, 1988: 11, 1989: 10, 1990: 10, 1991: 11, 1992: 8, 1993: 13, 1994: 12, 1995: 10, 1996: 10, 1997: 10, 1998: 7, 1999: 10, 2000: 11, 2001: 8, 2002: 9, 2003: 10, 2004: 14, 2005: 12, 2006: 8, 2007: 9, 2008: 11, 2009: 9, 2010: 12, 2011: 10, 2012: 10, 2013: 11, 2014: 11, 2015: 9, 2016: 10, 2017: 11, 2018: 10, 2019: 11, 2020: 9, 2021: 10, 2022: 11, 2023: 8, 2024: 10, 2025: 11, 2026: 10, 2027: 9, 2028: 10, 2029: 9, 2030: 12, 2031: 10, 2032: 9, 2033: 10, 2034: 10, 2035: 10, 2036: 9, 2037: 10, 2038: 10, 2039: 10, 2040: 11, 2041: 12, 2042: 10, 2043: 11, 2044: 11, 2045: 10, 2046: 9, 2047: 11, 2048: 10, 2049: 10, 2050: 10, 2051: 9, 2052: 10, 2053: 9, 2054: 10, 2055: 7, 2056: 11, 2057: 11, 2058: 10, 2059: 10, 2060: 12, 2061: 10, 2062: 9, 2063: 11, 2064: 9, 2065: 11, 2066: 11, 2067: 10, 2068: 16, 2069: 9, 2070: 9, 2071: 11, 2072: 11, 2073: 10, 2074: 11, 2075: 10, 2076: 9, 2077: 9, 2078: 9, 2079: 10, 2080: 10, 2081: 11, 2082: 10, 2083: 10, 2084: 10, 2085: 10, 2086: 11, 2087: 9, 2088: 12, 2089: 10, 2090: 9, 2091: 10, 2092: 11, 2093: 12, 2094: 12, 2095: 10, 2096: 10, 2097: 10, 2098: 11, 2099: 10, 2100: 11, 2101: 11, 2102: 11, 2103: 10, 2104: 9, 2105: 11, 2106: 9, 2107: 11, 2108: 11, 2109: 10, 2110: 9, 2111: 12, 2112: 8, 2113: 10, 2114: 10, 2115: 10, 2116: 11, 2117: 10, 2118: 8, 2119: 9, 2120: 13, 2121: 10, 2122: 10, 2123: 10, 2124: 11, 2125: 11, 2126: 11, 2127: 11, 2128: 10, 2129: 14, 2130: 11, 2131: 11, 2132: 9, 2133: 10, 2134: 11, 2135: 12, 2136: 9, 2137: 13, 2138: 10, 2139: 10, 2140: 10, 2141: 9, 2142: 11, 2143: 10, 2144: 11, 2145: 12, 2146: 11, 2147: 10, 2148: 8, 2149: 9, 2150: 12, 2151: 10, 2152: 9, 2153: 11, 2154: 10, 2155: 8, 2156: 10, 2157: 10, 2158: 10, 2159: 10, 2160: 11, 2161: 10, 2162: 10, 2163: 9, 2164: 8, 2165: 11, 2166: 10, 2167: 

15. Contar cuantos registros nulos hay en cada columna y la cantidad de valores únicos en la misma, y almacenarlo en un diccionario que tenga de clave el indice el nombre de la columna

El output debería ser el siguiente:
``` sql
{'año': [0, 1],
 'secretaria': [0, 1],
 'nombreestablecimiento': [0, 2387],
 'zona': [0, 3],
 'direccion': [0, 2377],
 'telefono': [62, 2329],
 'nombre_Rector': [0, 2354],
 'tipo_Establecimiento': [0, 2],
 'etnias': [2333, 12],
 'sector': [2404, 1],
 'genero': [2404, 1],
 'niveles': [16, 19],
 'jornadas': [13, 42],
 'caracter': [2404, 1],
 'especialidad': [1110, 22],
 'grados': [16, 181],
 'modelos_Educativos': [38, 33],
 'capacidades_Excepcionales': [2394, 5],
 'discapacidades': [1890, 125],
 'idiomas': [1461, 8],
 'numero_de_Sedes': [0, 7],
 'estado': [2404, 1],
 'prestador_de_Servicio': [0, 10],
 'propiedad_Planta_Fisica': [0, 10],
 'resguardo': [0, 2],
 'matricula_Contratada': [0, 2],
 'calendario': [0, 3],
 'internado': [2404, 1],
 'estrato_Socio_Economico': [2400, 3],
 'correo_Electronico': [428, 1962]}
```

In [57]:
dicc = {}
for i in data.columns:
    nulos = data.loc[:,i].isnull()
    total_nulos = sum(nulos)
    
    unicos = data.loc[:,i].unique()
    total_unicos = len(unicos)

    dicc[i] = [total_nulos, total_unicos]
dicc

{'año': [0, 1],
 'secretaria': [0, 1],
 'nombreestablecimiento': [0, 2387],
 'zona': [0, 3],
 'direccion': [0, 2377],
 'telefono': [62, 2329],
 'nombre_Rector': [0, 2354],
 'tipo_Establecimiento': [0, 2],
 'etnias': [2333, 12],
 'sector': [2404, 1],
 'genero': [2404, 1],
 'niveles': [16, 19],
 'jornadas': [13, 42],
 'caracter': [2404, 1],
 'especialidad': [1110, 22],
 'grados': [16, 181],
 'modelos_Educativos': [38, 33],
 'capacidades_Excepcionales': [2394, 5],
 'discapacidades': [1890, 125],
 'idiomas': [1461, 8],
 'numero_de_Sedes': [0, 7],
 'estado': [2404, 1],
 'prestador_de_Servicio': [0, 10],
 'propiedad_Planta_Fisica': [0, 10],
 'resguardo': [0, 2],
 'matricula_Contratada': [0, 2],
 'calendario': [0, 3],
 'internado': [2404, 1],
 'estrato_Socio_Economico': [2400, 3],
 'correo_Electronico': [428, 1962]}

16. Realiza una copia de la data en el objeto "data_bis" para no modificar la data original y completa los valores faltantes de la columna "modelos_Educativos" con el valor del registro previo

In [59]:
data_bis = data.copy()

In [60]:
data_bis["modelos_Educativos"] = data_bis["modelos_Educativos"].ffill()

17. Realiza una copia de la data en el objeto "data_bis" para no modificar la data original y completa los valores faltantes de la columna "jornadas" con el valor más frecuente de dicha columna

In [62]:
data_bis = data.copy()

In [63]:
# opcion 1
valor = data_bis["jornadas"].value_counts().index[0]
data_bis["jornadas"] = data_bis["jornadas"].fillna(valor)

In [64]:
# opcion 2
valor = data_bis["jornadas"].mode()
data_bis["jornadas"] = data_bis["jornadas"].fillna(valor)

18. Filtrar la tabla para mostrar los registros de zona "URBANA"

In [66]:
data.query("zona == 'URBANA'")

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
0,2016,BOGOTA,INST DE BTO TEC COMERCIAL PITAGORAS ...,URBANA,KR 5 11 67,5665677 / 3429092,YOLANDA ARIAS CRUZ,Institucion,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pitagoras@pitagoras.edu.co
1,2016,BOGOTA,GIMNASIO INFANTIL FEDERICO FROEBEL,URBANA,CL 32 SUR 52 A 54,7100349,SANDRA MILENA MENDEZ,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,gimfedebel@hotmail.com
2,2016,BOGOTA,GIMNASIO INFANTIL LOS NIÑOS DEL MAÑANA,URBANA,CL 134 D 47 27,6010350,CLAUDIA BOCACHICA SAENZ,Institucion,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,claudialindenibocachica@hotmail.com
3,2016,BOGOTA,COLEGIO FRANCISCO PRIMERO S.S. (IED),URBANA,KR 28 63 64,2126019 -- 2481271,JOSE CUSTODIO GALARZA MORENO,Institucion,NaN,NaN,...,4,NaN,OFICIAL,OFICIAL,NO APLICA,NO,A,NaN,NaN,cedalemania12@redp.edu.co
4,2016,BOGOTA,COL SAN JUAN VIANETH ...,URBANA,KR 2 C 3 18 SUR,2804738 -- 4714934,GLORIA ESPERANZA CHUQUIN LAISECA,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,colegiosanjuanviateh@hotmail.com -- colegiosan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399,2016,BOGOTA,COLEGIO SAN JOSE DE CALASANZ,URBANA,CL 129 88 B 35,6854492 -- 6854495 -- 6803549,GLADIS CUÉLLAR IBAÑEZ,Institucion,NaN,NaN,...,1,NaN,COMUNIDAD RELIGIOSA,COMUNIDAD RELIGIOSA,NO APLICA,NO,A,NaN,NaN,csjcsuba@yahoo.es
2400,2016,BOGOTA,COL NUEVO REINO DE TURINGIA,URBANA,KR 103 B 152 C 34,6830915,RUTH CECILIA CORREA FAJARDO,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,jibnuevoreinodeturingia@hotmail.com - ruth_cec...
2401,2016,BOGOTA,LIC INF GOOFY ...,URBANA,CL 65 F SUR 78 C 32,7761739 / 7762538 / 7753157 /8045802,SANDRA PATRICIA SANTAMARIA OVALLE,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pattysantaco@yahoo.com directoragoofy@gmail....
2402,2016,BOGOTA,LIC APRENDO CON MIS AMIGOS ...,URBANA,CR. 94 NO.29-30,2671099,YANNETH CONSUELO BOLIVAR GAITAN,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,NaN
2403,2016,BOGOTA,JARD INF EL ROSAL DE MI INFANCIA ...,URBANA,TR. 56A NO.45-18 SUR,7242172,ADALGIZA LADINO,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,adalgizaladino@hotmail.com ...

19. Filtrar la tabla para mostrar los registros que no sean de calendario "A" y tengan menos de 5 sedes o por lo menos más de 1

In [68]:
data.query("calendario != 'A' and numero_de_Sedes >= 1 and numero_de_Sedes <= 5")

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
79,2016,BOGOTA,COL COLOMBO HEBREO ...,URBANA,AC 153 50 65,6711303 -- 6711263 -- 6711323,JORGE ALBERTO MEJIA GONZALEZ,Institucion,NaN,NaN,...,1,NaN,COMUNIDAD,COMUNIDAD,NO APLICA,NO,B,NaN,NaN,rectoria@cch.edu.co -- secacademica@cch.edu.co
94,2016,BOGOTA,INSTITUTO EL ROBLE,URBANA,CL 152 A 17 44,3222529,VLADIMIR ENRIQUE SERNA MOSQUERA,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,OTRO,NaN,NaN,instituto@elroble.edu.co
156,2016,BOGOTA,JARD INF MI PEQUEÑO MUNDO BARRETO GOMEZ Y CIA ...,URBANA,CL 131 77 04,2713638 -- 2713911 -- 2267914,MARIA MERCEDES GOMEZ DE MACALLISTER,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,B,NaN,NaN,mpm@mipequenomundo.edu.co
169,2016,BOGOTA,JARD INF TALLER DE ARTE ARCO IRIS ...,URBANA,CL 87 9 06,2363700 -- 5305521,MILDRED HELENA VENEGAS CONCHA,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,B,NaN,NaN,tallerdeartearcoiris@hotmail.com
170,2016,BOGOTA,COL COOP MINUTO DE DIOS ...,URBANA,IND TR 74 NO.82B-05,2510809 ext. 127 ...,MAURICIO BELTRÁN CASTRO,Institucion,NaN,NaN,...,1,NaN,COOPERATIVO,COOPERATIVO,NO APLICA,NO,OTRO,NaN,NaN,cemidminuto@hotmail.com ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2274,2016,BOGOTA,FUND NUEVO MARYMOUNT ...,URBANA,CL 169 B 74 A 02,6699077 - 6794545,MARIA ANGELA TORRES SOTO,Institucion,NaN,NaN,...,1,NaN,COOPERATIVO,COOPERATIVO,NO APLICA,NO,B,NaN,NaN,info@marymountbogota.edu.co
2282,2016,BOGOTA,COL CALATRAVA,URBANA,KR 80 156 95,6847860,CONSUELO VALDERRAMA MORALES,Institucion,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,B,NaN,NaN,info@colegiocalatrava.edu.co - rectoria@colegi...
2291,2016,BOGOTA,COL MONTESSORI BRITISH SCHOOL ...,URBANA,CL 128 72 80,6528585,CLAUDIA ESPERANZA DIAZ RUIZ,Institucion,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,B,NaN,NaN,calidad@mbs.edu.co -- administracion@mbs.edu.co
2331,2016,BOGOTA,COL ABRAHAM LINCOLN ...,URBANA,DG 170 59 57,6767360 / 6767367 / 6779800 ...,MILTON ANTONIO MARTINEZ VALERO,Institucion,NaN,NaN,...,1,NaN,FUNDACION O CORPORACIONES,FUNDACION O CORPORACIONES,NO APLICA,NO,B,NaN,NaN,rectoria@abrahamlincolin.edu.co ...
2347,2016,BOGOTA,COL. INTERNACIONAL DE EDUCACIÓN INTEGRAL - CIE...,RURAL,KM 3 VIA SUBA COTA,7569199 -- 6830604,FELIPE ANDRÉS PALACIOS GUTIÉRREZ,Institucion,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,B,NaN,NaN,info@ciedi.edu.co ciedi@openway.com.co

20. Filtrar la tabla para mostrar los registros que no tenga nulo la columna "niveles" y que no sea un registro que se encuentre posterior a la mitad de la tabla

In [70]:
# opcion 1
data.iloc[:int(data.shape[0]/2),:].dropna(subset=['niveles'])

# opcion 2
data.iloc[:int(data.shape[0]/2),:].query('niveles.notnull()')

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
0,2016,BOGOTA,INST DE BTO TEC COMERCIAL PITAGORAS ...,URBANA,KR 5 11 67,5665677 / 3429092,YOLANDA ARIAS CRUZ,Institucion,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pitagoras@pitagoras.edu.co
1,2016,BOGOTA,GIMNASIO INFANTIL FEDERICO FROEBEL,URBANA,CL 32 SUR 52 A 54,7100349,SANDRA MILENA MENDEZ,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,gimfedebel@hotmail.com
2,2016,BOGOTA,GIMNASIO INFANTIL LOS NIÑOS DEL MAÑANA,URBANA,CL 134 D 47 27,6010350,CLAUDIA BOCACHICA SAENZ,Institucion,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,claudialindenibocachica@hotmail.com
3,2016,BOGOTA,COLEGIO FRANCISCO PRIMERO S.S. (IED),URBANA,KR 28 63 64,2126019 -- 2481271,JOSE CUSTODIO GALARZA MORENO,Institucion,NaN,NaN,...,4,NaN,OFICIAL,OFICIAL,NO APLICA,NO,A,NaN,NaN,cedalemania12@redp.edu.co
4,2016,BOGOTA,COL SAN JUAN VIANETH ...,URBANA,KR 2 C 3 18 SUR,2804738 -- 4714934,GLORIA ESPERANZA CHUQUIN LAISECA,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,colegiosanjuanviateh@hotmail.com -- colegiosan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1197,2016,BOGOTA,LIC PEDAG LOS JILGUEROS ...,URBANA,DG 6 B 78 A 50,2929884 / 2927621 ...,MAGDALENA CRUZ NAVARRO,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,liceojilgueros@hotmail.com
1198,2016,BOGOTA,COLEGIO CAMPESTRE LOS PINOS,URBANA,CL 64 113 A 94,4336427,LUZ EMILIA MOLANO BEJARANO,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,colegiopinos@hotmail.com
1199,2016,BOGOTA,GIMN PSICOPEDAG GENESIS ...,URBANA,CR. 87 NO.54-56 SUR,4506119,GLADYS FETECUA,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,NaN
1200,2016,BOGOTA,COL NSTRA SRA DE LA SALINA ...,URBANA,CLL. 71A NO.92-04,2527363,NANCY HERRERA CUERVO,Centro,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,colnssalinas@hotmail.com ...
1201,2016,BOGOTA,COL DE NSTRA SRA DEL ROSARIO ...,URBANA,CL 4 57 49,4202307 -- 2606329 -- 5637411,SOR NOHORA YOLANDA RODRIGUEZ GOMEZ,Institucion,NaN,NaN,...,1,NaN,COMUNIDAD RELIGIOSA,COMUNIDAD RELIGIOSA,NO APLICA,NO,A,NaN,NaN,rectoria@colrosariobogota.edu.co